# Generated by Django 3.2.12 on 2023-11-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_dailytopic_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytopic',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
