# Generated by Django 3.2.12 on 2023-11-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travallo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.IntegerField(),
        ),
    ]
